// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs0SrI1ngetnLi2FEzz9AhhyatjbRHtmk',
    appId: '1:999550911680:web:6c2cc25dbac05bdb6a9925',
    messagingSenderId: '999550911680',
    projectId: 'bookingsystem-51d39',
    authDomain: 'bookingsystem-51d39.firebaseapp.com',
    storageBucket: 'bookingsystem-51d39.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8MUltlDlD4KnHOQSKrw6WnXRg1rSt1b4',
    appId: '1:999550911680:android:507268c22e43dc8a6a9925',
    messagingSenderId: '999550911680',
    projectId: 'bookingsystem-51d39',
    storageBucket: 'bookingsystem-51d39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsqurE42Bkrtp5Xu3bIMlgvxvwrRUPDd8',
    appId: '1:999550911680:ios:4894f568c5a894406a9925',
    messagingSenderId: '999550911680',
    projectId: 'bookingsystem-51d39',
    storageBucket: 'bookingsystem-51d39.firebasestorage.app',
    iosBundleId: 'com.example.bookingsystem',
  );
}
